// <auto-generated />
using JSL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JSL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210630232948_TabelaViagens")]
    partial class TabelaViagens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JSL.Models.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cidadeMotorista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enderecoMotorista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoMotorista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marcaCaminhao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modeloCaminhao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeMotorista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placaCaminhao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qntEixos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("JSL.Models.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("date")
                        .HasColumnType("int");

                    b.Property<int>("KmTotal")
                        .HasColumnType("int");

                    b.Property<string>("LocalEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalSaida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("motoristaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("motoristaId");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("JSL.Models.Viagem", b =>
                {
                    b.HasOne("JSL.Models.Motorista", "Motorista")
                        .WithMany("Viagens")
                        .HasForeignKey("motoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("JSL.Models.Motorista", b =>
                {
                    b.Navigation("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
